name: Update GitHub Profile Blogs
on: push

jobs:

  dispatch:
    permissions: write-all
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['Voltonik/Voltonik']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --request POST \
            --data '{"event_type": "blog_update", "client_payload": { }}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
